FROM openjdk:18
COPY ./addressbook-sse-fullstack-0.0.1-SNAPSHOT.jar addressbook-sse-fullstack-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "./addressbook-sse-fullstack-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
